---
# yamllint disable rule:line-length
#
# https://golangci-lint.run/usage/configuration/
# https://golangci-lint.run/usage/linters/#enabled-by-default-linters
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  allow-parallel-runners: true
linters:
  enable:
    - asasalint  # https://github.com/alingse/asasalint
    - asciicheck  # https://github.com/tdakkota/asciicheck
    - bidichk  # https://github.com/breml/bidichk
    - bodyclose  # https://github.com/timakin/bodyclose
    - canonicalheader  # https://github.com/lasiar/canonicalHeader
    - containedctx  # https://github.com/sivchari/containedctx
    - contextcheck  # https://github.com/kkHAIKE/contextcheck
    - copyloopvar  # https://github.com/karamaru-alpha/copyloopvar
    - dogsled  # https://github.com/alexkohler/dogsled
    - durationcheck  # https://github.com/charithe/durationcheck
    - errcheck  # https://github.com/kisielk/errcheck
    - errchkjson  # https://github.com/breml/errchkjson
    - errname  # https://github.com/Antonboom/errname
    - errorlint  # https://github.com/polyfloyd/go-errorlint
    - exhaustive  # https://github.com/nishanths/exhaustive
    - exportloopref  # https://github.com/kyoh86/exportloopref
    - fatcontext  # https://github.com/Crocmagnon/fatcontext
    - forcetypeassert  # https://github.com/gostaticanalysis/forcetypeassert
    - goconst  # https://github.com/jgautheron/goconst
    - gocritic  # https://github.com/go-critic/go-critic
    - gofumpt  # https://github.com/mvdan/gofumpt
    - goimports  # https://pkg.go.dev/golang.org/x/tools/cmd/goimports
    - gosec  # https://github.com/securego/gosec
    - gosimple  # https://github.com/dominikh/go-tools/tree/master/simple
    - govet  # https://pkg.go.dev/cmd/vet
    - inamedparam  # https://github.com/macabu/inamedparam
    - ineffassign  # https://github.com/gordonklaus/ineffassign
    - intrange  # https://github.com/ckaznocha/intrange
    - makezero  # https://github.com/ashanbrown/makezero
    - mirror  # https://github.com/butuzov/mirror
    - misspell  # https://github.com/client9/misspell
    - mnd  # https://github.com/tommy-muehle/go-mnd
    - musttag  # https://github.com/go-simpler/musttag
    - nilerr  # https://github.com/gostaticanalysis/nilerr
    - perfsprint  # https://github.com/catenacyber/perfsprint
    - prealloc  # https://github.com/alexkohler/prealloc
    - predeclared  # https://github.com/nishanths/predeclared
    - revive  # https://github.com/mgechev/revive
    - staticcheck  # https://staticcheck.io/
    - stylecheck  # https://github.com/dominikh/go-tools
    - tenv  # https://github.com/sivchari/tenv
    - thelper  # https://github.com/kulti/thelper
    - typecheck  # https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors
    - unconvert  # https://github.com/mdempsky/unconvert
    - unparam  # https://github.com/mvdan/unparam
    - unused  # https://github.com/dominikh/go-tools/tree/master/unused
    - usestdlibvars  # https://github.com/sashamelentyev/usestdlibvars
    - vet
    - wrapcheck  # https://github.com/tomarrell/wrapcheck
  disable:
    - godot  # just ended up being annoying (can use regexp exclude in .godot.yaml -- https://github.com/tetafro/godot)
# https://github.com/mgechev/revive#configuration
# https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
#
# To validate things from outside of code editor, run:
# golangci-lint run -v
linters-settings:
  goconst:
    min-occurrences: 4
  misspell:
    ignore-words:
      - "Nominet"
  revive:
    enable-all-rules: true
    rules:
      - name: "add-constant"
        severity: "warning"
        arguments:
          - maxLitCount: "10"
            allowInts: "0,1,2,3,4,5"
        disabled: true  # most of the time it's fine, and the performance isn't a concern
      - name: "argument-limit"
        severity: "warning"
        arguments: [6]
      - name: "atomic"
        severity: "warning"
      - name: "bare-return"
        severity: "warning"
      - name: "bool-literal-in-expr"
        severity: "warning"
      - name: "cognitive-complexity"
        arguments: [40]
        disabled: true  # most of the time you don't have time to rewrite/refactor
      - name: "comment-spacings"
        arguments: ["lint:ignore", "exhaustive:ignore", "codespell:ignore"]
      - name: "confusing-naming"
        severity: "warning"
      - name: "confusing-results"
        severity: "warning"
      - name: "constant-logical-expr"
        severity: "error"
      - name: "context-as-argument"
        severity: "error"
      - name: "context-keys-type"
        severity: "error"
      - name: "cyclomatic"
        arguments: [50]
        disabled: true  # most of the time you don't have time to rewrite/refactor
      # - name: "datarace"
      #   severity: "error"
      - name: "deep-exit"
        severity: "warning"
      - name: "defer"
        severity: "warning"
      - name: "early-return"
        severity: "warning"
      - name: "empty-block"
        severity: "error"
      - name: "empty-lines"
        severity: "warning"
      - name: "error-naming"
        severity: "error"
      - name: "error-return"
        severity: "error"
      - name: "error-strings"
        severity: "error"
      - name: "errorf"
        severity: "warning"
      - name: "exported"
        severity: "error"
      - name: "flag-parameter"
        severity: "warning"
      - name: "function-result-limit"
        severity: "warning"
        arguments: [4]
      - name: "function-length"
        severity: "warning"
        arguments: [50, 0]
      - name: "get-return"
        severity: "error"
      - name: "identical-branches"
        severity: "error"
      - name: "if-return"
        severity: "warning"
      - name: "increment-decrement"
        severity: "error"
      - name: "indent-error-flow"
        severity: "warning"
      - name: "import-shadowing"
        severity: "warning"
      - name: "line-length-limit"
        disabled: true
      - name: "max-public-structs"
        arguments: [10]
      - name: "modifies-parameter"
        severity: "warning"
      - name: "modifies-value-receiver"
        severity: "warning"
      - name: "nested-structs"
        severity: "warning"
      - name: "optimize-operands-order"
        severity: "warning"
      - name: "package-comments"
        severity: "warning"
      - name: "range"
        severity: "warning"
      - name: "range-val-in-closure"
        severity: "warning"
      - name: "range-val-address"
        severity: "warning"
      - name: "receiver-naming"
        severity: "warning"
      - name: "redefines-builtin-id"
        severity: "error"
      - name: "string-of-int"
        severity: "warning"
      - name: "struct-tag"
        severity: "warning"
      - name: "superfluous-else"
        severity: "warning"
      - name: "time-equal"
        severity: "warning"
      - name: "time-naming"
        severity: "warning"
      - name: "var-declaration"
        severity: "warning"
      - name: "var-naming"
        severity: "warning"
      - name: "unconditional-recursion"
        severity: "error"
      - name: "unexported-naming"
        severity: "warning"
      - name: "unexported-return"
        severity: "error"
      - name: "unhandled-error"
        severity: "warning"
        arguments:
          - "fmt.Print"
          - "fmt.Printf"
          - "fmt.Println"
          - "fmt.Fprint"
          - "fmt.Fprintf"
          - "fmt.Fprintln"
      - name: "unnecessary-stmt"
        severity: "warning"
      - name: "unreachable-code"
        severity: "warning"
      - name: "unused-parameter"
        severity: "warning"
      - name: "unused-receiver"
        severity: "warning"
        disabled: true
      - name: "use-any"
        severity: "warning"
      - name: "useless-break"
        severity: "warning"
      - name: "waitgroup-by-value"
        severity: "warning"
