vim.keymap.set("n", "<leader>dpc", "<Cmd>lua require('dap').continue()<CR>", { desc = "start debugging" })
vim.keymap.set("n", "<leader>dpo", "<Cmd>lua require('dap').step_over()<CR>", { desc = "step over" })
vim.keymap.set("n", "<leader>dpi", "<Cmd>lua require('dap').step_into()<CR>", { desc = "step into" })
vim.keymap.set("n", "<leader>dpt", "<Cmd>lua require('dap').step_out()<CR>", { desc = "step out" })
vim.keymap.set("n", "<leader>dpb", "<Cmd>lua require('dap').toggle_breakpoint()<CR>", { desc = "toggle breakpoint" })
vim.keymap.set("n", "<leader>dpv", "<Cmd>lua require'dap'.set_breakpoint(vim.fn.input('Breakpoint condition: '))<CR>", { desc = "toggle breakpoint" })
vim.keymap.set("n", "<leader>dpr", "<Cmd>lua require('dap').repl.open()<CR>", { desc = "open repl" })
vim.keymap.set("n", "<leader>dpu", "<Cmd>lua require('dapui').toggle()<CR>", { desc = "toggle dap ui" })
